apiVersion: v1
kind: Service
metadata:
  name: bf-project-mysql
spec:
  selector:
    app: bf-project-mysql
  ports:
  - name: mysql-port
    port: 3306
    targetPort: 3306
    protocol: TCP
  type: LoadBalancer