apiVersion: v1
kind: ConfigMap
metadata:
  name: bf-project-mysql-configmap
data:
  my.cnf: |
    [client]
    default-character-set=utf8mb4
    [mysql]
    default-character-set=utf8mb4
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    datadir=/var/lib/mysql
    max_connections=2000
    sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    default-authentication-plugin=mysql_native_password
    log-bin=/var/lib/mysql/mysql-bin
    log-short-format
    log-error=/var/log/mysql/error.log
    general_log
    general_log_file=/var/log/mysql/general.log
    slow_query_log
    long_query_time=2
    slow_query_log_file=/var/log/mysql/slow.log
    [mysqldump]
    default-character-set=utf8mb4
    quick
    max_allowed_packet=512M
    [myisamchk]
    key_buffer_size=256M
    sort_buffer_size=256M
    read_buffer=2M
    write_buffer=2M